services:
  webApi:
    image: freelancerprojectmanagerserver
    build:
      context: .
      dockerfile: FreelancerProjectManager.Server/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data.mi:/var/lib/postgresql/data
