services:
  webApi:
    image: freelancerprojectmanagerserver
    build:
      context: .
      dockerfile: FreelancerProjectManager.Server/Dockerfile
    ports:
      - "5451:8080"
      - "5452:8081"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5450:5432"
    volumes:
      - ./data.mi:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
